member_index:
    pattern:   /
    defaults:  { _controller: BuntsuuMainBundle:Member:index }
    
member_search:
    pattern:   /search
    defaults:  { _controller: BuntsuuMainBundle:Member:search }

member_profile:
    pattern:   /profile
    defaults:  { _controller: BuntsuuMainBundle:Member:profile }
    
member_profile_target:
    pattern:   /profile/{target}
    defaults:  { _controller: BuntsuuMainBundle:Member:profileTarget }

member_preference:
    pattern:  /preference
    defaults: { _controller : BuntsuuMainBundle:Member:preference }

member_stamp:
    pattern:   /stamp
    defaults:  { _controller: BuntsuuMainBundle:Member:stamp }

member_chat:
    pattern:   /chat
    defaults:  { _controller: BuntsuuMainBundle:Member:chat }
    
member_chat_message:
    pattern:   /chat/add
    defaults:  { _controller: BuntsuuMainBundle:Member:addMessage }

member_chat_target:
    pattern:   /chat/target
    defaults:  { _controller: BuntsuuMainBundle:Member:selectTarget }
