# app/config/security.yml
security:
    encoders:
        "Buntsuu\MainBundle\Entity\User":        
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
    role_hierarchy:
         ROLE_ADMIN: ROLE_USER
         ROLE_SUPER_ADMIN: ROLE_ADMINISTRATOR
    
    providers:
        main:
            entity: { class : BuntsuuMainBundle:User, property:username }
        administrators:
            entity: { class: BuntsuuMainBundle:User }
                 
    firewalls:
        main:      
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                success_handler: my.success_handler
                login_path:  /
                check_path:  /login_check
              
    access_control:
        - { path: ^/admin, roles: ROLE_ADMINISTRATOR }
        - { path: ^/member, roles: ROLE_USER}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

