<?php

namespace Buntsuu\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	
	public function userTarget($id)
	{
		$qb = $this->createQueryBuilder('m')
		->join('m.author','a')
		->join('m.target','t')
		->select('t.username as target','a.username as author')
		->distinct()
		->where(' t.id = :id OR a.id = :id ')
		->setParameter('id', $id);
	
		return $qb->getQuery()->getResult();
	}
	
	public function getConversationBetween($id,$username)
	{
		$qb = $this->createQueryBuilder('m')
		->join('m.author','a')
		->join('m.target','t')
		->where(' t.id = :id AND a.username = :username OR t.username = :username AND a.id = :id')
		->setParameter('id', $id)
		->setParameter('username', $username);
	
		return $qb->getQuery()->getResult();
	}
	
}