<?php

namespace Buntsuu\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StampRepository extends EntityRepository
{
}