parameters:
#    buntsuu_main.example.class: Buntsuu\MainBundle\Example

services:
#    buntsuu_main.example:
#        class: %buntsuu_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    my.success_handler:
        class:   Buntsuu\MainBundle\Authentication\SuccessHandler
        arguments: [@router, @security.context]